### ISSUE TITLE
toolbox.zig is out of date with current syntax

### ISSUE THREAD

**Issue by qt-dork** [DanB91/UPWARD-for-Playdate#3]
can't write a stack trace in the simulator on [toolbox.zig](https://github.com/DanB91/UPWARD-for-Playdate/blob/8e086691b513594d9491fefa49774dc03ac6077d/modules/toolbox/src/toolbox.zig#L93) because `std.debug.detectTTYConfig()` no longer exists. it's since been graduated to `std.io.tty.detectConfig(file: File)` as mentioned in [this proposal](https://github.com/ziglang/zig/issues/15804).

Affected line:
```zig
std.debug.writeCurrentStackTrace(stream.writer(), debug_info, std.debug.detectTTYConfig(), null) catch {};
```

i normally wouldn't mention this in a finished project, but you mention it in [zig playdate template](https://github.com/DanB91/Zig-Playdate-Template) when mentioning that you only get 10kb of stack space, i figured it was prudent to mention it here, for any beginners that might be looking to it as a reference.

> You only get 10KB of stack space. That's it. I have not tested much of Zig's std on the Playdate, but std was not designed for a stack this small. See how far you can get, but you might want to write a lightweight "toolbox" library, like I did for UPWARD.  std.fmt.bufPrintZ works well, though!

**Comment by DanB91** [comment]
Thanks for letting me know about this! I actually realized I forgot to actually use the panic handler.   Just pushed a commit to fix this and update the panic handler to the one in my Zig-Playdate-Template: https://github.com/DanB91/UPWARD-for-Playdate/blob/main/modules/toolbox/src/toolbox.zig#L102
